{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.localbroadcastmanager",
    "module": "localbroadcastmanager",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "localbroadcastmanager-1.1.0.aar",
          "url": "localbroadcastmanager-1.1.0.aar",
          "size": 7607,
          "sha512": "d1e217671114b809a0f1c01e0a8b7225e081595c1e6edd02249c6a7b2b555b9b82f63d244f353bf93d50129b9ea7aff2da2b109d3e90fa43e79c5ac24ae08dd9",
          "sha256": "a22b94a77789f3b34becd24082231300524011ccc83f026142c49ad60131379b",
          "sha1": "4e8850d599ec17c3c3e9b15f507e943fc9507313",
          "md5": "a3e0812200bba02459dc5afb72310d5f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "localbroadcastmanager-1.1.0.aar",
          "url": "localbroadcastmanager-1.1.0.aar",
          "size": 7607,
          "sha512": "d1e217671114b809a0f1c01e0a8b7225e081595c1e6edd02249c6a7b2b555b9b82f63d244f353bf93d50129b9ea7aff2da2b109d3e90fa43e79c5ac24ae08dd9",
          "sha256": "a22b94a77789f3b34becd24082231300524011ccc83f026142c49ad60131379b",
          "sha1": "4e8850d599ec17c3c3e9b15f507e943fc9507313",
          "md5": "a3e0812200bba02459dc5afb72310d5f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "localbroadcastmanager-1.1.0-sources.jar",
          "url": "localbroadcastmanager-1.1.0-sources.jar",
          "size": 4258,
          "sha512": "c395d7df3ab5a0460720d6c87c74d2da87023a6bc339e573be927468e0a0d779bb27ef88ca78ce4081a42d014478385a6b9aa419fbf68b12e7a2fe151cce889b",
          "sha256": "d6c25fd6fe6dadf78986971c2158d1f15c56296eaaced9fc6eda5edbddabc746",
          "sha1": "5e883f600e4fe297c01cdff938ca5bf582bf6020",
          "md5": "61b832f212959d3f3e055644ea626792"
        }
      ]
    }
  ]
}
