{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-play-services",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "4irbk5x6kragle63hngfxoqfii"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.6.1.jar",
          "url": "kotlinx-coroutines-play-services-1.6.1.jar",
          "size": 13053,
          "sha512": "b06c2983074caac6203581e4275c2a3f1f1f6f4c3bf588bd2cd2c1d33723876237889fafd759c8013413c542552c4dd2929eab7c2435b71f8d7a60d578b054be",
          "sha256": "b6284eff3470375ed2f3b1c35bc35c04b4996141d5708aa728383b2ab9670d48",
          "sha1": "4a3877d9838cb26ba12186604397259f89dbc820",
          "md5": "4928ebbf6cd403eca0353568e8cd3ede"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-tasks",
          "version": {
            "requires": "16.0.1"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-play-services-1.6.1.jar",
          "url": "kotlinx-coroutines-play-services-1.6.1.jar",
          "size": 13053,
          "sha512": "b06c2983074caac6203581e4275c2a3f1f1f6f4c3bf588bd2cd2c1d33723876237889fafd759c8013413c542552c4dd2929eab7c2435b71f8d7a60d578b054be",
          "sha256": "b6284eff3470375ed2f3b1c35bc35c04b4996141d5708aa728383b2ab9670d48",
          "sha1": "4a3877d9838cb26ba12186604397259f89dbc820",
          "md5": "4928ebbf6cd403eca0353568e8cd3ede"
        }
      ]
    }
  ]
}
